### PR TITLE
Fixing transaction pool add transaction behaviour

### LINKED ISSUE #1132: Transaction events triggered twice in transaction process
The method `TransactionPoolImpl.addTransactions` invokes `TransactionPoolImpl.addTransaction`. If the transactions are accepted as new pending transactions, both methods trigger the events `onPendingTransactionsReceived` and `onTransactionPoolChanged` TWICE.

It's not the expected behaviour, and it could lead to additional spurious execution.

### PR DESCRIPTION
**Pull request by ajlopez**
The method `TransactionPoolImpl.addTransaction` was modified to consider the adding of queued successors.

This modificacion fixes #1132 and #1130  The tests mentioned in #1130 were added and run without failure.

### CODE REVIEW

File: rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java [hunk 1]
```diff
@@ -158,37 +158,49 @@ private RepositorySnapshot getCurrentRepository() {
         return repositoryLocator.snapshotAt(getBestBlock().getHeader());
     }
 
-    @Override
-    public synchronized List<Transaction> addTransactions(final List<Transaction> txs) {
+    private List<Transaction> addSuccesors(Transaction tx) {
```
Comment (Vovchyk) [inline rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java:161]: @ajlopez, It seems to me that `addSuccesors` and `getQueuedSuccesor` methods could be merged into single one? So we'd reduce a number of paths through the `queuedTransactions` collection.

File: rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java [hunk 2]
```diff
@@ -158,37 +158,49 @@ private RepositorySnapshot getCurrentRepository() {
...
-                    queuedTransactions.removeTransactionByHash(found.getHash());
+        while (succesor.isPresent()) {
+            Transaction found = succesor.get();
+            queuedTransactions.removeTransactionByHash(found.getHash());
 
-                    if (!this.addTransaction(found).transactionWasAdded()) {
-                        break;
-                    }
+            if (!this.internalAddTransaction(found).transactionWasAdded()) {
+                break;
```
Comment (Vovchyk) [inline rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java:170]: should we `break` here? `getQueuedSuccesor` method returns the first tx from the collection of transactions with the same nonce. There might be some other tx with the same nonce which potentially could be added? Another question: should the `getQueuedSuccesor` method return the first tx or the oldest one (from the list of txs with the same nonce)?

Comment (nicops) [reply rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java:170]: re: _There might be some other tx with the same nonce which potentially could be added?_, NO, but because the queuedTransactions collection is a TransactionSet, which is a particular class that doesn't allow more than one tx with the same nonce, see: https://github.com/rsksmart/rskj/blob/918e14623851fc58aaf3b7a39d2ef680adbc686f/rskj-core/src/main/java/org/ethereum/core/TransactionSet.java#L44

The way the method works is that the new tx always removes any preexisting tx with the same nonce in the TransactionSet.

File: rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java [hunk 3]
```diff
@@ -252,14 +264,25 @@ public synchronized TransactionPoolAddResult addTransaction(final Transaction tx
...
-        if (listener != null) {
-            EventDispatchThread.invokeLater(() -> {
-                listener.onPendingTransactionsReceived(Collections.singletonList(tx));
-                listener.onTransactionPoolChanged(TransactionPoolImpl.this);
-            });
+        return TransactionPoolAddResult.ok();
+    }
+
+    @Override
+    public synchronized TransactionPoolAddResult addTransaction(final Transaction tx) {
```
Comment (nicops) [inline rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java:271]: I would rewrite this to call addTransactions with a list of one to avoid duplicated logic, but it's a minor detail

File: rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java (hunk 1 above)
Comment (ajlopez) [reply rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java:161]: but `getQueuedSuccesor` is called TWICE from `addSuccesors` in two different logic

File: rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java (hunk 2 above)
Comment (ajlopez) [reply rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java:170]: Originally, transaction pool allowed many transactions from the same sender with the same nonce (with different values, and then, different hash). The last implementors decided to not allow such case. I'm not sure it is the right way. Maybe the client/user changed their intention, and the put another competing transaction, to replace an old one. Maybe we should review other implementations (geth, parity). 

But now, there are no transactions with same sender, same nonce

File: rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java (hunk 1 above)
Comment (Vovchyk) [reply rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java:161]: I guess the current version is pretty sustainable and it's more about refactoring, reducing the amount of code and personal preference )

something like:

```java
        Map<BigInteger, Transaction> txMap = queuedTransactions.getTransactionsWithSender(tx.getSender()).stream()
                .collect(Collectors.toMap(Transaction::getNonceAsInteger, t -> t));

        Transaction nextSuccessor;
        BigInteger nextNonce = tx.getNonceAsInteger().add(BigInteger.ONE);
        while ((nextSuccessor = txMap.get(nextNonce)) != null && internalAddTransaction(nextSuccessor).transactionWasAdded()) {
            added.add(nextSuccessor);
            nextNonce = nextNonce.add(BigInteger.ONE);
        }
```

I also noticed a type in the `getQueuedSuccesor` method name and that `getTransactionsWithSender` cannot return `null`, so no need to check for `null` inside the `getQueuedSuccesor` method.


Inside the `getTransactionsWithSender` method I'd replace `return new ArrayList<>();` onto `Collections.emptyList()`, even though it's not related to the pull request.

**Comment by patogallaiovlabs** [comment]
pipeline:run

**Comment by patogallaiovlabs** [comment]
pipeline:run

**Comment by patogallaiovlabs** [comment]
pipeline:run

**Comment by josedahlquist** [comment]
pipeline: run

File: rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java (hunk 3 above)
Comment (ajlopezrsk) [reply rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java:263]: Well, the `addTransactions` method returns a list of transaction, that it was the original intention of the method. Maybe we could use this results in the (possible) removal of `TransactionGateway`, to return to the original behavior: `TransactionPool` returns the added transactions, to be relayed to the other nodes by the caller object. So, we would visit this refactor in that upcoming issue

File: rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java (hunk 1 above)
Comment (ajlopezrsk) [reply rskj-core/src/main/java/co/rsk/core/bc/TransactionPoolImpl.java:161]: OK, now using `Collections.emptyList()` and typos fixed, thanks!

**Comment by ajlopezrsk** [comment]
run: pipeline

**Comment by patogallaiovlabs** [comment]
pipeline:run

**Comment by patogallaiovlabs** [comment]
pipeline:run

**Comment by ajlopezrsk** [comment]
pipeline:run

**Comment by ajlopezrsk** [comment]
pipeline:run
